# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Killarney Medical Centre
email: info@killarneymedicalcentre.ie
description: > # this means to ignore newlines until "baseurl:"
  Killarney Medical Centre is a GP practice located close to Killarney town centre.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.killarneymedicalcentre.ie" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
collections:
  services:
    output: true
  staff:

